//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWSEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EWSEditor.Resources.DisplayStrings", typeof(DisplayStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to create EWSEditor log file at {0}.  Logging will be disabled for this session. ähnelt.
        /// </summary>
        internal static string FailCreateLogFileException {
            get {
                return ResourceManager.GetString("FailCreateLogFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to download the Exchange Web Services Managed API ähnelt.
        /// </summary>
        internal static string MSG_EWS_API_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("MSG_EWS_API_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impersonation configuration is invalid. ähnelt.
        /// </summary>
        internal static string MSG_IMPERSON_REQ {
            get {
                return ResourceManager.GetString("MSG_IMPERSON_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no attachments on this item to display. ähnelt.
        /// </summary>
        internal static string MSG_NO_ATTACHMENTS {
            get {
                return ResourceManager.GetString("MSG_NO_ATTACHMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EWSEditor cannot start because it could not find the Exchange Web Service Managed API (Microsoft.Exchange.WebServices.DLL) installed on this machine. ähnelt.
        /// </summary>
        internal static string MSG_NO_EWS_API {
            get {
                return ResourceManager.GetString("MSG_NO_EWS_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must configure a service URL either using Autodiscover or explicitly specifying one. ähnelt.
        /// </summary>
        internal static string MSG_SERVICE_REQ {
            get {
                return ResourceManager.GetString("MSG_SERVICE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To use specific credentials you must input at least a user name and password. ähnelt.
        /// </summary>
        internal static string MSG_SPECIFY_CREDS {
            get {
                return ResourceManager.GetString("MSG_SPECIFY_CREDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Associated items in {0} ähnelt.
        /// </summary>
        internal static string TITLE_CONTENTS_ASSOC {
            get {
                return ResourceManager.GetString("TITLE_CONTENTS_ASSOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items in {0} ähnelt.
        /// </summary>
        internal static string TITLE_CONTENTS_FOLDER {
            get {
                return ResourceManager.GetString("TITLE_CONTENTS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soft deleted tems in {0} ähnelt.
        /// </summary>
        internal static string TITLE_CONTENTS_SOFT {
            get {
                return ResourceManager.GetString("TITLE_CONTENTS_SOFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications ähnelt.
        /// </summary>
        internal static string TITLE_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("TITLE_NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notifications from {0} ähnelt.
        /// </summary>
        internal static string TITLE_NOTIFICATIONS_FOLDER {
            get {
                return ResourceManager.GetString("TITLE_NOTIFICATIONS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More appointments were returned in the search but only the first {0} will be displayed. ähnelt.
        /// </summary>
        internal static string WARN_CALENDARVIEW_LIMT {
            get {
                return ResourceManager.GetString("WARN_CALENDARVIEW_LIMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log message not found. ähnelt.
        /// </summary>
        internal static string WARN_EWS_LOG_MESSAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("WARN_EWS_LOG_MESSAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EWSEditor does not currently display more than 1000 items in the contents view.  This folder has more items in it, only the first 1000 are displayed. ähnelt.
        /// </summary>
        internal static string WARN_ITEM_VIEW_COUNT_LIMIT {
            get {
                return ResourceManager.GetString("WARN_ITEM_VIEW_COUNT_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no binding selected. ähnelt.
        /// </summary>
        internal static string WARN_NO_BINDING {
            get {
                return ResourceManager.GetString("WARN_NO_BINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no folder selected. ähnelt.
        /// </summary>
        internal static string WARN_NO_FOLDER {
            get {
                return ResourceManager.GetString("WARN_NO_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select individual schema properties, not a schema name. ähnelt.
        /// </summary>
        internal static string WARN_SELECT_SCHEMA_PROPS {
            get {
                return ResourceManager.GetString("WARN_SELECT_SCHEMA_PROPS", resourceCulture);
            }
        }
    }
}
